// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqtsgmvcegkjuskggeal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxdHNnbXZjZWdranVza2dnZWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0ODk2ODAsImV4cCI6MjA1NDA2NTY4MH0.xQwvK9iFzj1SPClD-9UC3-WTMRZKKFNMZv3IROjfz0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);